import React,{useEffect,useState} from 'react';import{createRoot}from'react-dom/client';import{BookOpen,ShoppingCart,Heart,ChefHat,Scale,Info,Clock,ChevronLeft,ChevronRight,Play,Pause,Square}from'lucide-react';import'./style.css';

type Step={title:string;text:string;help?:string;timer?:number};
const recipe={title:'Velouté de butternut',category:'Entrée',yield:'2,3 kg',cook:'≈ 30 min',ingredients:['200 g d’oignons','1 kg de butternut','200 g de blancs de poireaux','Curcuma','Eau','Sel','Poivre','Beurre'],steps:[
{title:'Préparer les légumes',text:'Laver tous les légumes, puis les éplucher.',help:'Éplucher consiste à retirer la peau extérieure avec un économe ou un couteau adapté.'},
{title:'Découper les légumes',text:'Couper le butternut en gros morceaux et émincer les oignons puis les poireaux.',help:'Émincer signifie couper en tranches fines et régulières.'},
{title:'Faire fondre le beurre',text:'Faire fondre une noix de beurre dans une casserole.'},
{title:'Faire revenir oignons et poireaux',text:'Ajouter les oignons émincés et les faire revenir doucement, sans coloration, puis ajouter les poireaux.',help:'Faire revenir doucement : cuire à feu modéré sans laisser brunir les légumes.'},
{title:'Ajouter le butternut',text:'Ajouter les morceaux de butternut dans la casserole.'},
{title:'Assaisonner',text:'Ajouter le sel, le poivre et le curcuma.'},
{title:'Ajouter l’eau',text:'Recouvrir d’eau à hauteur.',help:'À hauteur signifie ajouter juste assez de liquide pour arriver au niveau des aliments.'},
{title:'Cuire les légumes',text:'Laisser cuire environ 30 minutes, jusqu’à ce que les légumes soient bien tendres.',timer:30},
{title:'Mixer le velouté',text:'Mixer la soupe afin d’obtenir une texture lisse et ajuster la quantité d’eau selon la consistance souhaitée.',help:'Mixer jusqu’à obtenir une texture homogène, puis détendre progressivement avec de l’eau si nécessaire.'}] as Step[]};

function App(){const[page,setPage]=useState<'home'|'recipe'|'cook'|'shopping'|'convert'>('home');const[step,setStep]=useState(0);const[help,setHelp]=useState(false);const[seconds,setSeconds]=useState(1800);const[running,setRunning]=useState(false);const[amount,setAmount]=useState('1');const[from,setFrom]=useState('L');const[to,setTo]=useState('mL');
useEffect(()=>{if(!running)return;const id=setInterval(()=>setSeconds(s=>s>0?s-1:0),1000);return()=>clearInterval(id)},[running]);
const convert=()=>{const v=Number(amount)||0;const units:any={L:1000,cL:10,mL:1,kg:1000,g:1,mg:.001};if((['L','cL','mL'].includes(from)&&['L','cL','mL'].includes(to))||(['kg','g','mg'].includes(from)&&['kg','g','mg'].includes(to)))return (v*units[from]/units[to]).toLocaleString('fr-FR');return '—'};
const nav=(p:any,label:string,Icon:any)=><button className={page===p?'nav active':'nav'} onClick={()=>setPage(p)}><Icon size={19}/><span>{label}</span></button>;
if(page==='cook'){const s=recipe.steps[step];return <main className="cook"><header className="cooktop"><button onClick={()=>setPage('recipe')}><ChevronLeft/>Quitter</button><b>Étape {step+1} / {recipe.steps.length}</b><div className="progress"><i style={{width:`${(step+1)/recipe.steps.length*100}%`}}/></div></header><section className="step"><div><span className="eyebrow">ÉTAPE {step+1}</span><h1>{s.title}</h1><p>{s.text}</p>{s.help&&<><button className="outline" onClick={()=>setHelp(!help)}>👩‍🍳 JE NE SAIS PAS FAIRE</button>{help&&<div className="tip"><b>Conseil de Chef Sophie</b><p>{s.help}</p></div>}</>}{s.timer&&<div className="timer"><Clock/><div><small>MINUTEUR</small><strong>{String(Math.floor(seconds/60)).padStart(2,'0')}:{String(seconds%60).padStart(2,'0')}</strong></div><button onClick={()=>setRunning(!running)}>{running?<Pause/>:<Play/>}</button><button onClick={()=>{setRunning(false);setSeconds(1800)}}><Square/></button></div>}</div><aside className="chef"><div className="chefAvatar">👩‍🍳</div><h3>Chef Sophie</h3><p>Votre commis pédagogique vous accompagne à chaque étape.</p></aside></section><footer className="stepnav"><button disabled={step===0} onClick={()=>{setStep(step-1);setHelp(false)}}><ChevronLeft/> Étape précédente</button>{step<8?<button className="primary" onClick={()=>{setStep(step+1);setHelp(false)}}>Étape suivante <ChevronRight/></button>:<button className="primary" onClick={()=>setPage('home')}>Recette terminée ✓</button>}</footer></main>}
return <div className="app"><aside className="sidebar"><div className="brands"><img src="/daq2630-logo.png"/><img src="/online-formapro-logo.png"/></div>{nav('home','Catalogue',BookOpen)}{nav('shopping','Liste de courses',ShoppingCart)}<button className="nav"><Heart size={19}/><span>Favoris</span></button><div className="sep"/><button className="nav" onClick={()=>setPage('recipe')}><ChefHat size={19}/><span>Mode Je cuisine</span></button>{nav('convert','Convertisseur',Scale)}<button className="nav"><Info size={19}/><span>Aides techniques</span></button><div className="sophieMini">👩‍🍳<b>Chef Sophie</b><small>Votre aide pédagogique</small></div></aside><main className="content">
{page==='home'&&<><header><span className="eyebrow">DAQ2630 CUISINE</span><h1>Catalogue des recettes</h1><p>Apprendre • Comprendre • Réussir</p></header><div className="search">Rechercher une recette…</div><div className="filters"><b>Toutes les recettes</b><span>Entrées</span><span>Plats</span><span>Accompagnements</span><span>Desserts</span><span>Pâtisserie</span></div><div className="grid"><article className="card featured" onClick={()=>setPage('recipe')}><div className="food">🥣</div><span>Entrée</span><h2>Velouté de butternut</h2><p>Une recette douce et pédagogique, expliquée pas à pas.</p><div className="meta"><Clock size={16}/> {recipe.cook} · {recipe.yield}</div><button className="primary">Voir la recette</button></article><article className="card muted"><div className="food">🥧</div><span>À venir</span><h2>Les prochaines recettes</h2><p>Le catalogue s’enrichira progressivement depuis l’administration.</p></article></div></>}
{page==='recipe'&&<><button className="back" onClick={()=>setPage('home')}>← Catalogue</button><header><span className="eyebrow">{recipe.category}</span><h1>{recipe.title}</h1><p>Quantité finale : <b>{recipe.yield}</b> · Cuisson : <b>{recipe.cook}</b></p></header><div className="recipeLayout"><section className="panel"><h2>Ingrédients</h2><ul>{recipe.ingredients.map(x=><li key={x}>{x}</li>)}</ul><button className="outline" onClick={()=>setPage('shopping')}><ShoppingCart/> Ajouter à la liste de courses</button></section><section className="panel"><h2>Avant de commencer</h2><p>Préparez vos ingrédients et votre matériel. Chef Sophie pourra expliquer les gestes techniques pendant la recette.</p><h3>Ustensiles</h3><div className="utensils"><span>🔪 Couteau</span><span>🪵 Planche</span><span>🍲 Casserole</span><span>🥄 Louche</span><span>⚡ Mixeur</span></div><button className="primary big" onClick={()=>{setStep(0);setPage('cook')}}>COMMENCER LA RECETTE</button></section></div></>}
{page==='shopping'&&<><header><span className="eyebrow">OUTIL</span><h1>Liste de courses</h1><p>Les ingrédients des recettes sélectionnées seront regroupés ici.</p></header><section className="panel shopping"><h2>{recipe.title}</h2>{recipe.ingredients.map(x=><label key={x}><input type="checkbox"/> {x}</label>)}</section></>}
{page==='convert'&&<><header><span className="eyebrow">OUTIL DE CUISINE</span><h1>Convertisseur</h1><p>Conversions rapides sans quitter votre recette.</p></header><section className="panel converter"><input value={amount} onChange={e=>setAmount(e.target.value)}/><select value={from} onChange={e=>setFrom(e.target.value)}>{['L','cL','mL','kg','g','mg'].map(x=><option>{x}</option>)}</select><b>→</b><select value={to} onChange={e=>setTo(e.target.value)}>{['L','cL','mL','kg','g','mg'].map(x=><option>{x}</option>)}</select><strong>{convert()} {to}</strong><small>Les conversions volume ↔ poids nécessitent de connaître l’ingrédient et seront ajoutées ultérieurement.</small></section></>}
</main></div>}
createRoot(document.getElementById('root')!).render(<App/>);