import React,{useEffect,useState}from'react';import{createRoot}from'react-dom/client';import{Home,BookOpen,Heart,ShoppingCart,ChefHat,Scale,Wrench,Settings,Clock,Users,Search,ChevronLeft,ChevronRight,Play,Pause,Square}from'lucide-react';import'./style.css';

const recipe={title:'Velouté de butternut',category:'Entrée',yield:'2,3 kg',prep:'15 min',cook:'≈ 30 min',ingredients:['200 g d’oignons','1 kg de butternut','200 g de blancs de poireaux','Curcuma','Eau','Sel','Poivre','Beurre'],utensils:['Couteau','Économe','Planche','Casserole','Louche','Mixeur'],steps:[
{title:'Préparer les légumes',text:'Laver tous les légumes, puis les éplucher.',help:'Éplucher consiste à retirer la peau extérieure avec un économe ou un couteau adapté.'},
{title:'Découper les légumes',text:'Couper le butternut en gros morceaux et émincer les oignons puis les poireaux.',help:'Émincer signifie couper finement et régulièrement.'},
{title:'Faire fondre le beurre',text:'Faire fondre une noix de beurre dans une casserole.'},
{title:'Faire revenir oignons et poireaux',text:'Ajouter les oignons et les faire revenir doucement, sans coloration, puis ajouter les poireaux.',help:'Faire revenir doucement : cuire à feu modéré sans brunir.'},
{title:'Ajouter le butternut',text:'Ajouter les morceaux de butternut dans la casserole.'},
{title:'Assaisonner',text:'Ajouter le sel, le poivre et le curcuma.'},
{title:'Ajouter l’eau',text:'Recouvrir d’eau à hauteur.',help:'À hauteur : le liquide arrive au niveau des aliments.'},
{title:'Cuire les légumes',text:'Laisser cuire environ 30 minutes, jusqu’à ce que les légumes soient bien tendres.',timer:30},
{title:'Mixer le velouté',text:'Mixer pour obtenir une texture lisse et ajuster l’eau selon la consistance souhaitée.',help:'Mixer jusqu’à obtenir une texture homogène puis ajuster progressivement.'}
]};

function App(){const[page,setPage]=useState('home'),[step,setStep]=useState(0),[help,setHelp]=useState(false),[sec,setSec]=useState(1800),[run,setRun]=useState(false),[search,setSearch]=useState(''),[amount,setAmount]=useState('1'),[from,setFrom]=useState('L'),[to,setTo]=useState('mL');
useEffect(()=>{if(!run)return;const id=setInterval(()=>setSec(s=>s>0?s-1:0),1000);return()=>clearInterval(id)},[run]);
const nav=(p,l,I)=><button className={'nav '+(page===p?'active':'')} onClick={()=>setPage(p)}><I size={18}/><span>{l}</span></button>;
const convert=()=>{const v=Number(amount)||0,u={L:1000,cL:10,mL:1,kg:1000,g:1,mg:.001},vol=['L','cL','mL'],mass=['kg','g','mg'];if((vol.includes(from)&&vol.includes(to))||(mass.includes(from)&&mass.includes(to)))return (v*u[from]/u[to]).toLocaleString('fr-FR')+' '+to;return '—'};
if(page==='cook'){const s=recipe.steps[step];return <main className="cook"><header><button onClick={()=>setPage('recipe')}><ChevronLeft/></button><b>Étape {step+1} / 9</b><div className="progress"><i style={{width:(step+1)/9*100+'%'}}/></div><Clock size={18}/><span>{run?Math.floor(sec/60)+':'+String(sec%60).padStart(2,'0'):'12:00'}</span></header><section><img className="cookImg" src="/butternut.png"/><div className="cookText"><span className="kicker">ÉTAPE {step+1}</span><h1>{s.title}</h1><p>{s.text}</p>{s.help&&<><button className="outline" onClick={()=>setHelp(!help)}>👩‍🍳 JE NE SAIS PAS FAIRE</button>{help&&<div className="tip"><img src="/chef-sophie.png"/><div><b>Astuce de Chef Sophie</b><p>{s.help}</p></div></div>}</>}{s.timer&&<div className="timer"><Clock/><div><small>MINUTEUR</small><strong>{String(Math.floor(sec/60)).padStart(2,'0')}:{String(sec%60).padStart(2,'0')}</strong></div><button onClick={()=>setRun(!run)}>{run?<Pause/>:<Play/>}</button><button onClick={()=>{setRun(false);setSec(1800)}}><Square/></button></div>}</div></section><footer><button disabled={!step} onClick={()=>{setStep(step-1);setHelp(false)}}><ChevronLeft/> Étape précédente</button>{step<8?<button className="blue" onClick={()=>{setStep(step+1);setHelp(false)}}>Étape suivante <ChevronRight/></button>:<button className="blue" onClick={()=>setPage('home')}>Recette terminée</button>}</footer></main>}
return <div className="app"><aside><div className="brand"><img src="/daq2630-logo.png"/><img src="/online-formapro-logo.png"/></div>{nav('home','Catalogue',BookOpen)}{nav('shopping','Ma liste de courses',ShoppingCart)}<button className="nav"><Heart size={18}/><span>Mes favoris</span></button><small>JE CUISINE</small>{nav('recipe','Mode pas à pas',ChefHat)}<small>OUTILS</small>{nav('convert','Convertisseur',Scale)}{nav('utensils','Ustensiles',Wrench)}{nav('chef','Chef Sophie',ChefHat)}<button className="nav bottom"><Settings size={18}/><span>Paramètres</span></button></aside><main className="main">
{page==='home'&&<><div className="titleRow"><div><span className="kicker">LIVRE DE RECETTES NUMÉRIQUE PÉDAGOGIQUE</span><h1>Catalogue des recettes</h1><p>Des recettes pédagogiques, testées et expliquées pas à pas.</p></div><div className="miniChef"><img src="/chef-sophie.png"/><div><b>Chef Sophie</b><small>Votre commis pédagogique</small></div></div></div><div className="search"><Search size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Rechercher une recette…"/></div><div className="chips"><b>Toutes les recettes</b><span>Entrées</span><span>Plats</span><span>Accompagnements</span><span>Desserts</span><span>Pâtisseries</span><span>Bases</span></div><div className="cards"><article onClick={()=>setPage('recipe')}><img src="/butternut.png"/><div><span>Entrée</span><h3>Velouté de butternut</h3><p><Users size={14}/> 4 pers. <Clock size={14}/> 45 min</p></div></article>{['Gratin dauphinois','Moelleux au chocolat','Pâte à choux'].filter(x=>x.toLowerCase().includes(search.toLowerCase())).map((x,i)=><article className="soon" key={x}><div className="placeholder">{['🥔','🍫','🥐'][i]}</div><div><span>À venir</span><h3>{x}</h3><p>Prochaine recette du catalogue</p></div></article>)}</div><section className="book" onClick={()=>setPage('book')}><div><span className="kicker">CATALOGUE STYLE LIVRE DE CHEF</span><h2>Soupes & Veloutés</h2><p>Parcourez les recettes comme dans un vrai livre de cuisine.</p><button className="blue">Ouvrir le livre</button></div><img src="/butternut.png"/></section></>}
{page==='recipe'&&<><button className="back" onClick={()=>setPage('home')}>← Catalogue</button><section className="hero"><div><span className="kicker">{recipe.category}</span><h1>{recipe.title}</h1><p>Un velouté doux et réconfortant, conçu pour apprendre les gestes de base en cuisine.</p><div className="facts"><span><Clock/>Préparation <b>{recipe.prep}</b></span><span><Clock/>Cuisson <b>{recipe.cook}</b></span><span><Users/>Quantité <b>{recipe.yield}</b></span></div></div><img src="/butternut.png"/></section><div className="cols"><section className="panel"><h2>Ingrédients</h2><ul>{recipe.ingredients.map(x=><li key={x}>{x}</li>)}</ul><button className="outline" onClick={()=>setPage('shopping')}><ShoppingCart/> Ajouter à ma liste</button></section><section className="panel"><h2>Ustensiles nécessaires</h2><div className="utensils">{recipe.utensils.map((x,i)=><span key={x}>{['🔪','🥕','🪵','🍲','🥄','⚡'][i]}<b>{x}</b></span>)}</div><div className="tip"><img src="/chef-sophie.png"/><div><b>Chef Sophie vous accompagne</b><p>Utilisez « Je ne sais pas faire » lorsqu’un geste vous pose problème.</p></div></div><button className="blue big" onClick={()=>{setStep(0);setPage('cook')}}>COMMENCER LA RECETTE <ChevronRight/></button></section></div></>}
{page==='shopping'&&<><span className="kicker">OUTIL</span><h1>Ma liste de courses</h1><section className="panel shopping">{recipe.ingredients.map(x=><label key={x}><input type="checkbox"/> {x}</label>)}</section></>}
{page==='convert'&&<><span className="kicker">OUTIL</span><h1>Convertisseur</h1><section className="panel converter"><input value={amount} onChange={e=>setAmount(e.target.value)}/><select value={from} onChange={e=>setFrom(e.target.value)}>{['L','cL','mL','kg','g','mg'].map(x=><option>{x}</option>)}</select><b>→</b><select value={to} onChange={e=>setTo(e.target.value)}>{['L','cL','mL','kg','g','mg'].map(x=><option>{x}</option>)}</select><strong>{convert()}</strong><small>Les conversions volume ↔ poids seront liées à l’ingrédient plus tard.</small></section></>}
{page==='utensils'&&<><span className="kicker">OUTILS</span><h1>Ustensiles de cuisine</h1><div className="utensils large">{recipe.utensils.map((x,i)=><span key={x}>{['🔪','🥕','🪵','🍲','🥄','⚡'][i]}<b>{x}</b></span>)}</div></>}
{page==='chef'&&<section className="chefPage"><img src="/chef-sophie.png"/><div><span className="kicker">VOTRE COMMIS PÉDAGOGIQUE</span><h1>Chef Sophie</h1><p>Je vous aide à comprendre les gestes, à réussir vos étapes et à prendre confiance en cuisine.</p><div className="skills"><span>✓ J’explique les gestes</span><span>✓ Je donne des astuces</span><span>✓ Je vérifie vos étapes</span><span>✓ Je vous encourage</span></div></div></section>}
{page==='book'&&<section className="openBook"><div><span className="kicker">CHAPITRE 01</span><h1>Soupes & Veloutés</h1><p>Des recettes réconfortantes pour toutes les saisons.</p><span className="decor">🎃 🥕 🌿</span></div><div><img src="/butternut.png"/><h2>Velouté de butternut</h2><button className="blue" onClick={()=>setPage('recipe')}>Voir la recette</button></div></section>}
</main></div>}
createRoot(document.getElementById('root')).render(<App/>);